# Site settings
title: 'Code The Web'
description: 'Web development explained for normal people - Learn HTML, CSS and JavaScript in ways that you can actually understand!'
keyword: 'code the web, code the web blog, blog, web, web development, development, programming, internet, blog, website, html, css, javascript, learn, code, coding, learn to code, code web'
url: 'https://codetheweb.blog' # your host
baseurl: '/'

# Hide future posts
future: false

# Keep _redirects and _headers files in build
include: ['_redirects', '_headers']

# Navigation links
nav:
  home: '/'
  tags: '/tags'
  "newsletter &#127790; &#128640;": '/newsletter'

# Author
author: 'Ethan'
nickname: 'Ethan'
bio: "A self-taught programmer from Australia and creator of Code The Web. I program in HTML, CSS, JavaScript / NodeJS, Python and some random C++ release from the 90's."
avatar: 'assets/img/profile.png'

# Search
search: true

# Night mode
nightMode: true

# Comments
disqus: true
disqus_url: 'https://codetheweb-blog.disqus.com/embed.js'

# Share
social-share: true
social-share-items: ['facebook', 'twitter', 'google']

# theme color
theme-color: 'pink'  # pink or default

# Post header background patterns (when the post has no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'circuitBoard'

# SNS settings url: weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  github: 'https://github.com/Booligoosh'
  website: 'https://ethan.link/'
  #twitter: 'https://twitter.com/Booligoosh' (icon doesn't work for some reason)
  dribble: 'https://dribbble.com/Booligoosh'
  medium: 'https://medium.com/@Booligoosh'

# Tags
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value

# Build settings
paginate: 6
paginate_path: 'page:num'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md']

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  
# Image optimization
jekyll_image_optim:
  image_optim:
    allow_lossy: true

RSS: false

# Plugins
plugins: [jekyll-paginate, jekyll-sitemap]


# ME
sass:
  style: compressed
  
newsletter: /newsletter
share: '#share'
comments: '#disqus_thread'
learn: '/learn'
contact: /contact
repo: https://github.com/CodeTheWebBlog/CodeTheWebBlog.github.io/
permalink: pretty
sponsor: /sponsor
donate: https://buymeacoffee.com/CodeTheWeb
patreon: https://www.patreon.com/CodeTheWebBlog

ph-banner: false

email: '<span class="email"></span>'

social:
  facebook: 'https://fb.me/CodeTheWebBlog/'
  twitter: 'https://twitter.com/CodeTheWebBlog/'

wpm: 180

learn:
  html:
    tutorials: ['/2017/10/06/html-syntax/','/2017/10/07/structure-of-an-html-document/','/2017/10/09/basic-types-of-html-tags/','/2017/10/14/links-images-about-file-paths/','/2017/10/22/wrapping-and-grouping-elements/','/2017/10/29/lists-and-navigation/','/2017/12/14/html-icons/']
    
    other: ['/2017/12/10/steps-to-creating-a-website/','/2017/11/24/devchat/','/2017/12/16/web-development-reference-sites/','/2018/02/04/github-pages-free-hosting/']
    
  css:
    tutorials: ['/2017/11/11/css-syntax/','/2017/11/15/basic-css-properties/','/2017/11/17/css-sizing-and-positioning/','/2017/11/21/css-position-property/','/2017/11/29/css-display-property/','/2017/12/02/css-advanced-background-images/','/2017/12/04/css-units/','/2017/12/05/css-flexboxes/','/2017/12/07/fullscreen-image-hero/','/2017/12/12/style-a-navigation-bar-css/','/2018/01/17/css-text-properties-and-google-fonts/']
    
    other: ['/2017/12/10/steps-to-creating-a-website/','/2017/11/24/devchat/','/2017/12/16/web-development-reference-sites/','/2018/02/04/github-pages-free-hosting/']
    
  javascript:
    tutorials: ['/2018/02/12/hello-javascript/','/2018/02/25/javascript-variables/','/2018/02/28/if-statements-boolean-operators/','/2018/03/18/javascript-math/','/2018/03/25/for-and-while-loops-javascript/','/2018/04/05/javascript-functions/','/2018/04/28/javascript-arrays/','/2018/06/09/javascript-objects/','/2018/06/18/javascript-dom/', '/2019/01/21/javascript-url-parsing/']
    
    other: ['/2017/11/24/devchat/','/2017/12/16/web-development-reference-sites/','/2018/02/04/github-pages-free-hosting/']